18-349 Kernel: ads1015.h File Reference
ads1015.h File Reference
ADS1050 interface over I2C.
#include <kstdint.h>
Macros
#define ADS_ADDRESS 0x49
The address of ADS 0b1001000.
#define ADS_CONFIG_REG 0x01
The configure register of ADS.
#define ADS_CONVERS_REG 0x0
The conversion register of ADS.
#define ADS_CONTINU_CONFIG 0x0083
The continuous mode of ADS 0b0000 0100 1000 0011, PGA=000.
#define ADS_CHANNEL0_MASK 0x4000
The mask of AIN0.
#define ADS_CHANNEL1_MASK 0x5000
The mask of AIN1.
#define ADS_CHANNEL2_MASK 0x6000
The mask of AIN2.
#define ADS_CHANNEL3_MASK 0x7000
The mask of AIN3.
Functions
void adc_init (void)
initialize ADS1015
uint16_t adc_read (uint8_t channel)
Read a value from the ADC.
void display_light ()
Display the value of light.
void clap_detect ()
Clap detection. Loop for 1000 times and check the peak-to-peak difference.
Detailed Description
ADS1050 interface over I2C.
Date
12 Aug 2016
Author
James Mackaman jmack.nosp@m.ama@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu
Function Documentation
void adc_init (void)
initialize ADS1015
mainly doing debug output
References ADS_ADDRESS, i2c_master_read(), i2c_master_write(), and printk().
Referenced by kernel_main().
uint16_t adc_read (uint8_t channel)
Read a value from the ADC.
If the channel is the same with last time's, don't config. Else, config
Parameters
channel 0 through 3
Returns
the value read from the ADC
References adc_read_conversion(), adc_write_config(), ADS_CHANNEL0_MASK, ADS_CHANNEL1_MASK, ADS_CHANNEL2_MASK, ADS_CHANNEL3_MASK, and ADS_CONTINU_CONFIG.
Referenced by clap_detect(), and display_light().