18-349 Kernel: ads1015.c File Reference
ads1015.c File Reference
I2C driver for ads1015.
#include <kstdint.h>
#include <i2c.h>
#include <printk.h>
#include <ads1015.h>
Functions
void adc_write_config (uint16_t config_val)
write the configure value config_val to the config register
uint16_t adc_read_conversion ()
read the conversion register
void adc_init (void)
initialize ADS1015
uint16_t adc_read (uint8_t channel)
Read a value from the ADC.
void display_light ()
Display the value of light.
void clap_detect ()
Clap detection. Loop for 1000 times and check the peak-to-peak difference.
Detailed Description
I2C driver for ads1015.
Date
Sep 29, 2017
Author
John Zhong zhenz.nosp@m.2@an.nosp@m.drew..nosp@m.cmu..nosp@m.edu
Function Documentation
void adc_init (void)
initialize ADS1015
mainly doing debug output
References ADS_ADDRESS, i2c_master_read(), i2c_master_write(), and printk().
Referenced by kernel_main().
uint16_t adc_read (uint8_t channel)
Read a value from the ADC.
If the channel is the same with last time's, don't config. Else, config
Parameters
channel 0 through 3
Returns
the value read from the ADC
References adc_read_conversion(), adc_write_config(), ADS_CHANNEL0_MASK, ADS_CHANNEL1_MASK, ADS_CHANNEL2_MASK, ADS_CHANNEL3_MASK, and ADS_CONTINU_CONFIG.
Referenced by clap_detect(), and display_light().
uint16_t adc_read_conversion ()
read the conversion register
Returns
the value read from the conversion reg
References ADS_ADDRESS, ADS_CONVERS_REG, i2c_master_read(), i2c_master_write(), and printk().
Referenced by adc_read().
void adc_write_config (uint16_t config_val)
write the configure value config_val to the config register
Parameters
config_val The configure value to be written
References ADS_ADDRESS, ADS_CONFIG_REG, i2c_master_read(), i2c_master_write(), and printk().
Referenced by adc_read().