18-349 Kernel: i2c.h File Reference
i2c.h File Reference
I2C interface on rpi 2.
#include <kstdint.h>
#include <BCM2836.h>
Macros
#define I2C1_SDA 2
I2C DATA PINS, using GPIO 2.
#define I2C1_SCL 3
I2C CLOCK PINS, using GPIO 3.
#define BSC1_BASE 0x3f804000
Base Address of the BSC1 registers.
#define BSC_BASE_ADDR BSC1_BASE
We are using BSC1 for ads.
#define BSC_C_REG (volatile uint32_t *)(BSC_BASE_ADDR)
below are the define of BSC field
#define BSC_S_REG (volatile uint32_t *)(BSC_BASE_ADDR + 0x04)
BSC status register.
#define BSC_DLEN_REG (volatile uint32_t *)(BSC_BASE_ADDR + 0x08)
BSC Data Length Register.
#define BSC_A_REG (volatile uint32_t *)(BSC_BASE_ADDR + 0x0c)
BSC slave register.
#define BSC_FIFO_REG (volatile uint32_t *)(BSC_BASE_ADDR + 0x10)
BSC Data FIFO Register.
#define BSC_DIV_REG (volatile uint32_t *)(BSC_BASE_ADDR + 0x14)
BSC CLK divider Register.
#define BSC_C_I2CEN 0x8000
I2C Enable, 0 = disabled, 1 = enabled.
#define BSC_C_ST 0x0080
Start transfer, 1 = Start a new transfer.
#define BSC_C_CLEAR_1 0x0020
Clear FIFO Clear.
#define BSC_C_CLEAR_2 0x0010
Clear FIFO Clear.
#define BSC_C_READ 0x0001
Read transfer.
#define BSC_S_CLKT 0x00000200
Clock stretch timeout.
#define BSC_S_ERR 0x00000100
ACK error.
#define BSC_S_RXD 0x00000020
FIFO contains data.
#define BSC_S_TXD 0x00000010
FIFO can accept data.
#define BSC_S_DONE 0x00000002
Transfer DONE.
#define BSC_FIFO_MAX 16
The MAX size of BSC FIFO is 16 bytes.
#define I2C_REASON_OK 0x00
I2C transfer is success.
#define I2C_REASON_ERR_NACK 0x01
I2C transfer received an NACK, no slave device acknowledges the transfer.
#define I2C_REASON_ERR_TIMEOUT 0x02
I2C transfer clock stretch timeout.
#define I2C_CLK_100KHZ 0x5dc
When I2C Clock speed is 100KHZ, the value of the divider register should be 0x5dc.
Functions
void i2c_master_init (uint16_t clk)
initializes the I2C module
uint8_t i2c_master_write (uint8_t *buf, uint16_t len, uint8_t addr)
writes to I2C device
uint8_t i2c_master_read (uint8_t *buf, uint16_t len, uint8_t addr)
reads from I2C device
Detailed Description
I2C interface on rpi 2.
Date
Sep 29 2017
Author
John Zhong zhenz.nosp@m.2@an.nosp@m.drew..nosp@m.cmu..nosp@m.edu
Macro Definition Documentation
#define BSC_C_REG (volatile uint32_t *)(BSC_BASE_ADDR)
below are the define of BSC field
BSC control register
Referenced by i2c_master_read(), and i2c_master_write().
Function Documentation
void i2c_master_init (uint16_t clk)
initializes the I2C module
Parameters
clk bus clock speed
References BSC_DIV_REG, I2C1_SCL, and I2C1_SDA.
Referenced by kernel_main().
uint8_t i2c_master_read (uint8_t * buf, uint16_t len, uint8_t addr)
reads from I2C device
Parameters
buf pointer to input data buffer
len number of bytes to read
addr slave device address
Returns
0 means success, 1 means no slave address acknowledges, 2 means timeout
References BSC_A_REG, BSC_C_CLEAR_1, BSC_C_I2CEN, BSC_C_READ, BSC_C_REG, BSC_C_ST, BSC_DLEN_REG, BSC_FIFO_REG, BSC_S_CLKT, BSC_S_DONE, BSC_S_ERR, BSC_S_REG, BSC_S_RXD, I2C_REASON_ERR_NACK, I2C_REASON_ERR_TIMEOUT, I2C_REASON_OK, and printk().
Referenced by adc_init(), adc_read_conversion(), and adc_write_config().
uint8_t i2c_master_write (uint8_t * buf, uint16_t len, uint8_t addr)
writes to I2C device
Parameters
buf pointer to output data buffer
len length of output data buffer in bytes
addr slave device address
Returns
0 means success, 1 means no slave address acknowledges, 2 means timeout
References BSC_A_REG, BSC_C_CLEAR_2, BSC_C_I2CEN, BSC_C_REG, BSC_C_ST, BSC_DLEN_REG, BSC_FIFO_MAX, BSC_FIFO_REG, BSC_S_CLKT, BSC_S_DONE, BSC_S_ERR, BSC_S_REG, BSC_S_TXD, I2C_REASON_ERR_NACK, I2C_REASON_ERR_TIMEOUT, I2C_REASON_OK, and printk().
Referenced by adc_init(), adc_read_conversion(), and adc_write_config().