18-349 Kernel: printk.h File Reference
printk.h File Reference
kernel debugging routine
Functions
int printk (const char *fmt,...)
A kernel printf() function for debugging the kernel.
Detailed Description
kernel debugging routine
Date
August 28 2015
Author
Aaron Reyes areye.nosp@m.s@an.nosp@m.drew..nosp@m.cmu..nosp@m.edu
Function Documentation
int printk (const char * fmt, ...)
A kernel printf() function for debugging the kernel.
Parameters
fmt the format string
Returns
0 on success or -1 on failure
References printnumk(), and uart_put_byte().
Referenced by adc_init(), adc_read_conversion(), adc_write_config(), clap_detect(), display_light(), i2c_master_read(), i2c_master_write(), and uart_get_byte().