18-349 Kernel: uart.c File Reference
uart.c File Reference
lower level hardware interactions for uart on pi
#include <kstdint.h>
#include <gpio.h>
#include <printk.h>
Macros
#define MMIO_BASE_PHYSICAL 0x3F000000
All MMIO on the Raspberry Pi 2 begin at 0x3F000000.
#define AUXENB_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215004)
Auxiliary enables.
#define AUX_MU_DATA_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215040)
Hold the read/write data of mini UART.
#define AUX_MU_IER_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215044)
Mini UART interrupt enable.
#define AUX_MU_IIR_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215048)
Mini UART interrupt identify.
#define AUX_MU_LCR_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x21504c)
Mini UART line control.
#define AUX_MU_LSR_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215054)
Mini UART line status.
#define AUX_MU_BAUD_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215068)
Mini UART Baud Rate.
#define RX_PIN 15
GPIO UART RX pin.
#define TX_PIN 14
GPIO UART TX pin.
Functions
void uart_init (void)
initializes UART to 115200 baud in 8-bit mode
void uart_close (void)
closes UART
void uart_put_byte (uint8_t byte)
sends a byte over UART
uint8_t uart_get_byte (void)
reads a byte over UART
Detailed Description
lower level hardware interactions for uart on pi
Date
Sep 25 2017
Author
John Zhong zhenz.nosp@m.2@an.nosp@m.drew..nosp@m.cmu..nosp@m.edu
Function Documentation
uint8_t uart_get_byte (void)
reads a byte over UART
Returns
the byte received
References AUX_MU_DATA_REG, AUX_MU_LSR_REG, and printk().
Referenced by kernel_main().
void uart_put_byte (uint8_t byte)
sends a byte over UART
Parameters
byte the byte to send
References AUX_MU_DATA_REG, and AUX_MU_LSR_REG.
Referenced by printk(), and printnumk().